name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2#
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: build
        run: go build ./...
