name: Build
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello, World!
        run: echo "Hello, World!"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
